# Athom Smart Plug v1
substitutions:
  name: athom-plug-v1
  friendly_name: "Athom Smart Plug v1"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  captive_password: !secret captive_password

packages:
  piit79.base:
    url: https://github.com/piit79/esphome-configs
    file: base.yaml
    refresh: always

dashboard_import:
  package_import_url: github://piit79/esphome-configs/athom-smart-plug-v1.yaml@main

esphome:
  project:
    name: "piit79.athom-plug-v1"
    version: "1.0.0"
  name_add_mac_suffix: true

esp8266:
  board: esp8285
  restore_from_flash: true

preferences:
  flash_write_interval: 1min

select:
  - platform: template
    name: "Restore Mode"
    id: select_restore_mode
    options:
      - Always Off
      - Always On
      - Restore Default Off
      - Restore Default On
      - Restore Inverted Default Off
      - Restore Inverted Default On
    initial_option: "Always Off"
    optimistic: true
    restore_value: true
    on_value:
      - lambda: |-
          const SwitchRestoreMode restore_modes[6] = {
            SWITCH_ALWAYS_OFF,
            SWITCH_ALWAYS_ON,
            SWITCH_RESTORE_DEFAULT_OFF,
            SWITCH_RESTORE_DEFAULT_ON,
            SWITCH_RESTORE_INVERTED_DEFAULT_OFF,
            SWITCH_RESTORE_INVERTED_DEFAULT_ON
          };
          id(switch_socket).set_restore_mode(restore_modes[i]);

number:
  - platform: template
    id: on_power
    name: "Running Power"
    unit_of_measurement: W
    min_value: 1
    max_value: 3000
    initial_value: 20
    step: 1
    optimistic: true
    restore_value: true
    on_value:
      then:
        - lambda: id(device_running).set_upper_threshold(x);

  - platform: template
    id: on_delay
    name: "Running Delay"
    unit_of_measurement: s
    min_value: 0
    max_value: 120
    initial_value: 10
    step: 1
    optimistic: true
    restore_value: true

  - platform: template
    id: off_power
    name: "Stopped Power"
    unit_of_measurement: W
    min_value: 1
    max_value: 3000
    initial_value: 5
    step: 1
    optimistic: true
    restore_value: true
    on_value:
      then:
        - lambda: id(device_running).set_lower_threshold(x);

  - platform: template
    id: off_delay
    name: "Stopped Delay"
    unit_of_measurement: s
    min_value: 0
    max_value: 120
    initial_value: 10
    step: 1
    optimistic: true
    restore_value: true

binary_sensor:
  - platform: gpio
    id: button1
    internal: true
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: switch_socket

  - platform: analog_threshold
    id: device_running
    name: "Running"
    sensor_id: sensor_power_raw
    threshold:
      upper: 3000
      lower: 0
    filters:
      - delayed_on: !lambda "return id(on_delay).state * 1000;"
      - delayed_off: !lambda "return id(off_delay).state * 1000;"
    on_press:
      - lambda: |-
          id(led_status).turn_on().set_effect("slow_flash").perform();
    on_release:
      - light.turn_off: led_status

switch:
- platform: gpio
  name: "Socket"
  id: switch_socket
  icon: mdi:power-socket-eu
  pin: GPIO14
  on_turn_on:
    - lambda: |-
        id(sensor_hlw8012).stop_poller();
        id(sensor_hlw8012).set_update_interval(1000);
        id(sensor_hlw8012).start_poller();
  on_turn_off:
    - lambda: |-
        id(sensor_hlw8012).stop_poller();
        id(sensor_hlw8012).set_update_interval(15000);
        id(sensor_hlw8012).start_poller();

light:
  - platform: status_led
    id: led_status
    internal: true
    pin:
      number: GPIO13
      inverted: true
    effects:
      - strobe:
          name: slow_flash
          colors:
            - state: True
              duration: 2s
            - state: False
              duration: 2s

sensor:
  - platform: hlw8012
    id: sensor_hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO4
    cf1_pin: GPIO5
    voltage_divider: 780
    current:
      id: sensor_current_raw
      internal: true
      filters:
        - calibrate_linear:
          - 0.0000 -> 0.0110 # Relay off no load
          - 0.0097 -> 0.0260 # Relay on no load
          - 0.9270 -> 0.7570
          - 2.0133 -> 1.6330
          - 2.9307 -> 2.3750
          - 5.4848 -> 4.4210
          - 8.4308 -> 6.8330
          - 9.9171 -> 7.9830
        # Normalize for plug load
        - lambda: if (x < 0.0260) return 0; else return (x - 0.0260);
    voltage:
      id: sensor_voltage_raw
      internal: true

    power:
      id: sensor_power_raw
      internal: true
      unit_of_measurement: W
      filters:
        - calibrate_linear:
          - 0.0000 -> 0.5900 # Relay off no load
          - 0.0000 -> 1.5600 # Relay on no load
          - 198.5129 -> 87.8300
          - 434.2469 -> 189.5000
          - 628.6241 -> 273.9000
          - 1067.0067 -> 460.1000
          - 1619.8098 -> 699.2000
          - 2043.0282 -> 885.0000
        # Normalize for plug load
        - lambda: if (x < 1.5600) return 0; else return (x - 1.5600);
    change_mode_every: 1
    update_interval: 15s

  - platform: template
    name: "Voltage"
    icon: mdi:sine-wave
    unit_of_measurement: V
    accuracy_decimals: 1
    lambda: return id(sensor_voltage_raw).state;
    update_interval: 60s

  - platform: template
    name: "Current"
    icon: mdi:current-ac
    unit_of_measurement: A
    accuracy_decimals: 3
    lambda: return id(sensor_current_raw).state;
    update_interval: 15s

  - platform: template
    name: "Power"
    icon: mdi:flash
    unit_of_measurement: W
    accuracy_decimals: 1
    lambda: return id(sensor_power_raw).state;
    update_interval: 15s

  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: sensor_power_raw
    unit_of_measurement: kWh
    accuracy_decimals: 3
    restore: true
    filters:
      - multiply: 0.001  # Wh to kWh
      - delta: 0.001  # Only publish when there's at least 1 Wh of difference
