esphome:
  name: ${hostname}
  friendly_name: ${friendly_name}

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  ap:
    ssid: "esphome-${hostname}"
    password: ${captive_password}

captive_portal:
logger:
api:
ota:
web_server:
  port: 80
  version: 2

time:
  - platform: homeassistant
    id: time_ha

sensor:
  - platform: uptime
    id: sensor_uptime
    name: "Uptime"
    unit_of_measurement: days
    update_interval: 860s  # 0.01 * 1440 min = 14.4 min = 864 s
    accuracy_decimals: 2
    filters:
      - multiply: 0.000011574

  - platform: wifi_signal
    id: sensor_wifi_signal
    name: "Wi-Fi Signal"
    accuracy_decimals: 1
    update_interval: 300s

button:
  - platform: restart
    name: "Restart"
