substitutions:
  hostname: moon-light
  friendly_name: "Moon Light"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  captive_password: !secret captive_password

packages:
  piit79.base:
    url: https://github.com/piit79/esphome-configs
    file: base.yaml
    refresh: always

dashboard_import:
  package_import_url: github://piit79/esphome-configs/moon-light.yaml

esphome:
  name: ${hostname}
  project:
    name: "piit79.moon-light"
    version: "1.0.1"

esp8266:
  board: esp01_1m

binary_sensor:
  - platform: gpio
    id: push_button
    internal: true
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    on_press:
      - light.toggle: light1

  - platform: gpio
    id: rocker_switch
    internal: true
    pin:
      number: GPIO3
      mode:
        input: true
        pullup: true
      inverted: true
    on_state:
      - light.toggle: light1
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

output:
  - platform: gpio
    id: relay
    pin: GPIO12

light:
  - platform: binary
    id: light1
    name: None
    output: relay
    icon: mdi:moon-waning-crescent

status_led:
  pin:
    number: GPIO13
    inverted: yes
