esphome:
  name: poe-bt-proxy
  friendly_name: PoE Bluetooth Proxy
  project:
    name: "piit79.poe-bt-proxy"
    version: "1.0"
  min_version: 2024.6.0
  name_add_mac_suffix: true

packages:
  piit79.base:
    url: https://github.com/piit79/esphome-configs
    file: base.yaml
    refresh: always

dashboard_import:
  package_import_url: github://piit79/esphome-configs/poe-bt-proxy.yaml

esp32:
  board: esp32-poe
  framework:
    type: esp-idf

wifi: !remove
captive_portal: !remove

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin: GPIO17
    mode: CLK_OUT
  phy_addr: 0
  power_pin: GPIO12

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

sensor:
  - id: !remove sensor_wifi_signal
