# WiZ 60 Smart Bulb
substitutions:
  name: wiz60-bulb
  friendly_name: "WiZ 60 Bulb"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  captive_password: !secret captive_password

packages:
  piit79.base:
    url: https://github.com/piit79/esphome-configs
    file: base.yaml
    refresh: always

dashboard_import:
  package_import_url: github://piit79/esphome-configs/wiz60-bulb.yaml@main

esphome:
  project:
    name: "piit79.wiz60-bulb"
    version: "1.0.0"
  name_add_mac_suffix: true

esp8266:
  board: esp_wroom_02

output:
  - platform: esp8266_pwm
    pin: GPIO13
    frequency: 1000 Hz
    id: out_cw

  - platform: esp8266_pwm
    pin: GPIO4
    frequency: 1000 Hz
    id: out_ww

light:
  - platform: cwww
    name: None
    cold_white: out_cw
    warm_white: out_ww
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    constant_brightness: true

# remote_receiver:
#   pin:
#     number: GPIO5
#     inverted: True
#   dump: all
